
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Chat.Service.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Advertisement_Cat
{

    public int Ad_Cat_Id { get; set; }

    public string Ad_Cat_Name { get; set; }

    public string Ad_Cat_Reason { get; set; }

    public Nullable<System.DateTime> Dttm { get; set; }

}

}
