
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Chat.Service.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Country_State_city
{

    public int id { get; set; }

    public string L1 { get; set; }

    public string L2 { get; set; }

    public string L3 { get; set; }

    public string L4 { get; set; }

    public string Country { get; set; }

    public string State { get; set; }

    public string District { get; set; }

    public string City { get; set; }

}

}
