
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Chat.Service.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class G_CompanyMaster
{

    public int CoID { get; set; }

    public string CoName { get; set; }

    public string Address { get; set; }

    public string ContactNo { get; set; }

    public string ContactPerson { get; set; }

    public string Email { get; set; }

    public string URL { get; set; }

    public string RegNo { get; set; }

    public string SrvTaxNo { get; set; }

    public string TANNo { get; set; }

    public string PAN { get; set; }

    public string Logo { get; set; }

    public Nullable<int> UsID { get; set; }

    public string Status { get; set; }

    public string ChkSum { get; set; }

    public Nullable<System.DateTime> Dttm { get; set; }

    public Nullable<System.DateTime> PanDate { get; set; }

    public Nullable<System.DateTime> PanRenewDate { get; set; }

    public string PanCircle { get; set; }

    public string TDSNo { get; set; }

    public Nullable<System.DateTime> TDSDate { get; set; }

    public Nullable<System.DateTime> TdsRenewDate { get; set; }

    public string TdsCircle { get; set; }

    public string StNO { get; set; }

    public Nullable<System.DateTime> StDate { get; set; }

    public Nullable<System.DateTime> StRenewDate { get; set; }

    public string CstNo { get; set; }

    public Nullable<System.DateTime> CstDate { get; set; }

    public Nullable<System.DateTime> CstRenewDate { get; set; }

    public string ExciseNo { get; set; }

    public Nullable<System.DateTime> ExciseDate { get; set; }

    public Nullable<System.DateTime> ExciseRenewDate { get; set; }

    public string EccNo { get; set; }

    public Nullable<System.DateTime> EccDate { get; set; }

    public Nullable<System.DateTime> EccRenewDate { get; set; }

    public Nullable<System.DateTime> VatDate { get; set; }

    public Nullable<System.DateTime> VatRenewDate { get; set; }

    public string CompanyRagNo { get; set; }

    public string LicenceNo { get; set; }

    public string CompanyType { get; set; }

    public string BusinessType { get; set; }

    public string PinCode { get; set; }

    public string CID { get; set; }

    public string SID { get; set; }

    public string CIID { get; set; }

    public string VatNo1 { get; set; }

    public string OtherRegName1 { get; set; }

    public string OtherRegNo1 { get; set; }

    public string OtherRegName2 { get; set; }

    public string OtherRegNo2 { get; set; }

}

}
