
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Chat.Service.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Meeting_User
{

    public int MetTabId { get; set; }

    public Nullable<int> MetID { get; set; }

    public Nullable<int> MetUID { get; set; }

    public Nullable<int> Status { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<int> DataCreated { get; set; }

    public Nullable<int> IsDeleted { get; set; }

}

}
