
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Chat.Service.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Registration
{

    public int RegID { get; set; }

    public string Name { get; set; }

    public string Moblie { get; set; }

    public Nullable<int> Gender { get; set; }

    public int DepID { get; set; }

    public Nullable<System.DateTime> DOB { get; set; }

    public string Photo { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public string AboutSelf { get; set; }

    public Nullable<int> Status { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> DataCreated { get; set; }

    public Nullable<int> ModifyBy { get; set; }

    public Nullable<System.DateTime> DateModify { get; set; }

    public Nullable<int> IsDeleted { get; set; }

    public string IP { get; set; }

    public Nullable<int> Us_Id { get; set; }

    public Nullable<System.DateTime> LastActDate { get; set; }

    public string MobId { get; set; }

    public Nullable<int> MobType { get; set; }

    public string Otp { get; set; }

    public Nullable<int> OtpFlag { get; set; }

    public Nullable<System.DateTime> OtpDate { get; set; }

}

}
