//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.Service.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_Member
    {
        public int GrpMemtabid { get; set; }
        public Nullable<int> GrpID { get; set; }
        public Nullable<int> GrpMemid { get; set; }
        public Nullable<int> Status { get; set; }
        public string Ip { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    }
}
