//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.Service.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_Master
    {
        public int GrpID { get; set; }
        public string GroupName { get; set; }
        public string GIplmg { get; set; }
        public Nullable<int> GrpAdmin { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string IP { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    }
}
