//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.Service.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_Message
    {
        public int GroMsgld { get; set; }
        public Nullable<int> GrpID { get; set; }
        public Nullable<int> SenderID { get; set; }
        public string Message { get; set; }
        public string AudioURL { get; set; }
        public string VideoURL { get; set; }
        public string ImageURL { get; set; }
        public string FileURL { get; set; }
        public Nullable<int> MsgType { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string IP { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    }
}
