//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.Service.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting_Master
    {
        public int MetID { get; set; }
        public string MeetingTitle { get; set; }
        public string MeetingPlace { get; set; }
        public Nullable<System.DateTime> MeetingDate { get; set; }
        public string MeetingTime { get; set; }
        public Nullable<int> MeetingGenID { get; set; }
        public Nullable<int> MeetingType { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> DateCreated { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    }
}
