//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.Service.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opinion_Metting_Master
    {
        public int Opinionld { get; set; }
        public Nullable<int> MetID { get; set; }
        public string OpinionText { get; set; }
        public Nullable<int> OpinionType { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> DateCreated { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    }
}
