//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.Service.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SplashAdvMaster_2
    {
        public int Advld { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<System.DateTime> DateForm { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string RepTime { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> DataCreated { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> DateModify { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    }
}
