//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.Service.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Category
    {
        public int CoId { get; set; }
        public int UCatID { get; set; }
        public string UCatName { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Dttm { get; set; }
        public string ChkSum { get; set; }
        public Nullable<int> UsID { get; set; }
    }
}
