//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.Service.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor_Master
    {
        public int VendorId { get; set; }
        public string V_Name { get; set; }
        public string VOAddress { get; set; }
        public Nullable<int> VOGLId { get; set; }
        public Nullable<int> VOPinCode { get; set; }
        public string VOPhone1 { get; set; }
        public string VOPhone2 { get; set; }
        public string VFAddress { get; set; }
        public Nullable<int> VFGLId { get; set; }
        public Nullable<int> VFPinCode { get; set; }
        public string VFPhone1 { get; set; }
        public string VFPhone2 { get; set; }
        public string VBankName { get; set; }
        public string VBankIFSC { get; set; }
        public string VBankBranch { get; set; }
        public string VBankAcNo { get; set; }
        public string VEMailId { get; set; }
        public string VContactPerson { get; set; }
        public Nullable<System.DateTime> VCDOB { get; set; }
        public string VCMobile { get; set; }
        public string VSrTaxNo { get; set; }
        public Nullable<System.DateTime> VSrTaxDate { get; set; }
        public string VStNo { get; set; }
        public Nullable<System.DateTime> VStDate { get; set; }
        public string VCstNo { get; set; }
        public Nullable<System.DateTime> VCstDate { get; set; }
        public string VRegNo { get; set; }
        public Nullable<System.DateTime> VRegDate { get; set; }
        public string VPanNo { get; set; }
        public Nullable<System.DateTime> VPanDate { get; set; }
        public string VatNo { get; set; }
        public Nullable<System.DateTime> VatDate { get; set; }
        public Nullable<int> VCrLimit { get; set; }
        public Nullable<int> VCrDays { get; set; }
        public string VStatus { get; set; }
        public Nullable<System.DateTime> Dttm { get; set; }
        public Nullable<int> UsID { get; set; }
    }
}
